// Code generated by gen-manifest; DO NOT EDIT.

package system

import "github.com/lixenwraith/vi-fighter/internal/engine"

// Domain returns the declared state boundary for cursor.
func (*CursorSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for ping.
func (*PingSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for transient.
func (*TransientSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for camera.
func (*CameraSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for energy.
func (*EnergySystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for shield.
func (*ShieldSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for heat.
func (*HeatSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for boost.
func (*BoostSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for weapon.
func (*WeaponSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for typing.
func (*TypingSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for composite.
func (*CompositeSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for wall.
func (*WallSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for tower.
func (*TowerSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for gateway.
func (*GatewaySystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for loot.
func (*LootSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for glyph.
func (*GlyphSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for nugget.
func (*NuggetSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for decay.
func (*DecaySystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for blossom.
func (*BlossomSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for gold.
func (*GoldSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for materialize.
func (*MaterializeSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for cleaner.
func (*CleanerSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for fuse.
func (*FuseSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for spirit.
func (*SpiritSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for lightning.
func (*LightningSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for missile.
func (*MissileSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for navigation.
func (*NavigationSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for soft_collision.
func (*SoftCollisionSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for combat.
func (*CombatSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for drain.
func (*DrainSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for quasar.
func (*QuasarSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for swarm.
func (*SwarmSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for storm.
func (*StormSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for pylon.
func (*PylonSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for snake.
func (*SnakeSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for eye.
func (*EyeSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for bullet.
func (*BulletSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for dust.
func (*DustSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for flash.
func (*FlashSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for fadeout.
func (*FadeoutSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for marker.
func (*MarkerSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for explosion.
func (*ExplosionSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for motion_marker.
func (*MotionMarkerSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for splash.
func (*SplashSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for environment.
func (*EnvironmentSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for death.
func (*DeathSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for timekeeper.
func (*TimerSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Domain returns the declared state boundary for adaptation.
func (*AdaptationSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for genetic.
func (*GeneticSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Domain returns the declared state boundary for audio.
func (*AudioSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Domain returns the declared state boundary for music.
func (*MusicSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }
