// Code generated by gen-manifest; DO NOT EDIT.

package system

import "github.com/lixenwraith/vi-fighter/internal/engine"

// Domain returns the declared state boundary for cursor.
func (*CursorSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for cursor.
func (*CursorSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for ping.
func (*PingSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for ping.
func (*PingSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
	}
}

// Domain returns the declared state boundary for transient.
func (*TransientSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for transient.
func (*TransientSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for camera.
func (*CameraSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for camera.
func (*CameraSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
	}
}

// Domain returns the declared state boundary for energy.
func (*EnergySystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for energy.
func (*EnergySystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
	}
}

// Domain returns the declared state boundary for shield.
func (*ShieldSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for shield.
func (*ShieldSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
			"energy",
		},
	}
}

// Domain returns the declared state boundary for heat.
func (*HeatSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for heat.
func (*HeatSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
	}
}

// Domain returns the declared state boundary for boost.
func (*BoostSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for boost.
func (*BoostSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
	}
}

// Domain returns the declared state boundary for weapon.
func (*WeaponSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for weapon.
func (*WeaponSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
		Optional: []string{
			"combat",
			"cleaner",
			"missile",
			"energy",
		},
	}
}

// Domain returns the declared state boundary for typing.
func (*TypingSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for typing.
func (*TypingSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
		Optional: []string{
			"glyph",
			"death",
			"energy",
			"heat",
			"boost",
			"composite",
			"audio",
		},
	}
}

// Domain returns the declared state boundary for composite.
func (*CompositeSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for composite.
func (*CompositeSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"death",
		},
	}
}

// Domain returns the declared state boundary for wall.
func (*WallSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for wall.
func (*WallSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"cursor",
			"death",
			"fadeout",
		},
	}
}

// Domain returns the declared state boundary for tower.
func (*TowerSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for tower.
func (*TowerSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"composite",
			"combat",
			"death",
		},
		Optional: []string{
			"navigation",
		},
	}
}

// Domain returns the declared state boundary for gateway.
func (*GatewaySystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for gateway.
func (*GatewaySystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"navigation",
			"eye",
			"snake",
		},
	}
}

// Domain returns the declared state boundary for loot.
func (*LootSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for loot.
func (*LootSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
		Optional: []string{
			"death",
			"energy",
			"heat",
			"weapon",
			"flash",
		},
	}
}

// Domain returns the declared state boundary for glyph.
func (*GlyphSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for glyph.
func (*GlyphSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"wall",
		},
	}
}

// Domain returns the declared state boundary for nugget.
func (*NuggetSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for nugget.
func (*NuggetSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"cursor",
			"cleaner",
			"energy",
			"heat",
			"audio",
		},
	}
}

// Domain returns the declared state boundary for decay.
func (*DecaySystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for decay.
func (*DecaySystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"death",
		},
		Optional: []string{
			"glyph",
			"flash",
			"wall",
		},
	}
}

// Domain returns the declared state boundary for blossom.
func (*BlossomSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for blossom.
func (*BlossomSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"death",
		},
		Optional: []string{
			"glyph",
			"wall",
		},
	}
}

// Domain returns the declared state boundary for gold.
func (*GoldSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for gold.
func (*GoldSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
			"composite",
		},
		Optional: []string{
			"energy",
			"splash",
			"audio",
			"death",
		},
	}
}

// Domain returns the declared state boundary for materialize.
func (*MaterializeSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for materialize.
func (*MaterializeSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for cleaner.
func (*CleanerSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for cleaner.
func (*CleanerSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
		Optional: []string{
			"combat",
			"decay",
			"blossom",
			"audio",
		},
	}
}

// Domain returns the declared state boundary for fuse.
func (*FuseSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for fuse.
func (*FuseSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"drain",
		},
		Optional: []string{
			"materialize",
			"spirit",
			"quasar",
			"swarm",
		},
	}
}

// Domain returns the declared state boundary for spirit.
func (*SpiritSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for spirit.
func (*SpiritSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for lightning.
func (*LightningSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for lightning.
func (*LightningSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for missile.
func (*MissileSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for missile.
func (*MissileSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"explosion",
		},
		Optional: []string{
			"combat",
			"wall",
		},
	}
}

// Domain returns the declared state boundary for navigation.
func (*NavigationSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for navigation.
func (*NavigationSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"cursor",
			"wall",
		},
	}
}

// Domain returns the declared state boundary for soft_collision.
func (*SoftCollisionSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for soft_collision.
func (*SoftCollisionSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"drain",
			"quasar",
			"swarm",
			"storm",
			"pylon",
		},
	}
}

// Domain returns the declared state boundary for combat.
func (*CombatSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for combat.
func (*CombatSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"cursor",
			"energy",
			"lightning",
		},
	}
}

// Domain returns the declared state boundary for drain.
func (*DrainSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for drain.
func (*DrainSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
		Optional: []string{
			"combat",
			"materialize",
			"death",
			"flash",
			"dust",
		},
	}
}

// Domain returns the declared state boundary for quasar.
func (*QuasarSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for quasar.
func (*QuasarSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"composite",
			"combat",
			"death",
		},
		Optional: []string{
			"navigation",
			"lightning",
			"splash",
			"flash",
		},
	}
}

// Domain returns the declared state boundary for swarm.
func (*SwarmSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for swarm.
func (*SwarmSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"composite",
			"combat",
			"death",
		},
		Optional: []string{
			"navigation",
		},
	}
}

// Domain returns the declared state boundary for storm.
func (*StormSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for storm.
func (*StormSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"composite",
			"combat",
			"death",
		},
		Optional: []string{
			"navigation",
			"bullet",
			"materialize",
			"flash",
		},
	}
}

// Domain returns the declared state boundary for pylon.
func (*PylonSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for pylon.
func (*PylonSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"composite",
			"combat",
			"death",
		},
		Optional: []string{
			"navigation",
		},
	}
}

// Domain returns the declared state boundary for snake.
func (*SnakeSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for snake.
func (*SnakeSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"composite",
			"combat",
			"death",
		},
		Optional: []string{
			"navigation",
			"flash",
		},
	}
}

// Domain returns the declared state boundary for eye.
func (*EyeSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for eye.
func (*EyeSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"composite",
			"combat",
			"death",
		},
		Optional: []string{
			"navigation",
			"explosion",
		},
	}
}

// Domain returns the declared state boundary for bullet.
func (*BulletSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for bullet.
func (*BulletSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
		Optional: []string{
			"shield",
			"heat",
		},
	}
}

// Domain returns the declared state boundary for dust.
func (*DustSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for dust.
func (*DustSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"explosion",
		},
		Optional: []string{
			"flash",
			"death",
		},
	}
}

// Domain returns the declared state boundary for flash.
func (*FlashSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for flash.
func (*FlashSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for fadeout.
func (*FadeoutSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for fadeout.
func (*FadeoutSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for marker.
func (*MarkerSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for marker.
func (*MarkerSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for explosion.
func (*ExplosionSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for explosion.
func (*ExplosionSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"combat",
		},
	}
}

// Domain returns the declared state boundary for motion_marker.
func (*MotionMarkerSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for motion_marker.
func (*MotionMarkerSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
		Optional: []string{
			"glyph",
		},
	}
}

// Domain returns the declared state boundary for splash.
func (*SplashSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for splash.
func (*SplashSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"cursor",
		},
	}
}

// Domain returns the declared state boundary for environment.
func (*EnvironmentSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for environment.
func (*EnvironmentSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for death.
func (*DeathSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for death.
func (*DeathSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for timekeeper.
func (*TimerSystem) Domain() engine.SystemDomain { return engine.SystemDual }

// Dependencies returns the declared requirements for timekeeper.
func (*TimerSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"death",
		},
	}
}

// Domain returns the declared state boundary for adaptation.
func (*AdaptationSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for adaptation.
func (*AdaptationSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Required: []string{
			"navigation",
		},
		Optional: []string{
			"gateway",
		},
	}
}

// Domain returns the declared state boundary for genetic.
func (*GeneticSystem) Domain() engine.SystemDomain { return engine.SystemShared }

// Dependencies returns the declared requirements for genetic.
func (*GeneticSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"combat",
			"eye",
		},
	}
}

// Domain returns the declared state boundary for audio.
func (*AudioSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for audio.
func (*AudioSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{}
}

// Domain returns the declared state boundary for music.
func (*MusicSystem) Domain() engine.SystemDomain { return engine.SystemPlayer }

// Dependencies returns the declared requirements for music.
func (*MusicSystem) Dependencies() engine.SystemDependencies {
	return engine.SystemDependencies{
		Optional: []string{
			"audio",
		},
	}
}
