// Code generated by gen-manifest; DO NOT EDIT.

package engine

import (
	"github.com/lixenwraith/vi-fighter/component"
	"github.com/lixenwraith/vi-fighter/core"
)

// Component provides typed component store pointers
// Embedded in World, initialized once at world creation
type Component struct {
	Glyph       *Store[component.GlyphComponent]
	Sigil       *Store[component.SigilComponent]
	Nugget      *Store[component.NuggetComponent]
	Cursor      *Store[component.CursorComponent]
	Protection  *Store[component.ProtectionComponent]
	Kinetic     *Store[component.KineticComponent]
	Wall        *Store[component.WallComponent]
	Loot        *Store[component.LootComponent]
	Energy      *Store[component.EnergyComponent]
	Heat        *Store[component.HeatComponent]
	Shield      *Store[component.ShieldComponent]
	Boost       *Store[component.BoostComponent]
	Weapon      *Store[component.WeaponComponent]
	Orb         *Store[component.OrbComponent]
	Ping        *Store[component.PingComponent]
	Decay       *Store[component.DecayComponent]
	Blossom     *Store[component.BlossomComponent]
	Cleaner     *Store[component.CleanerComponent]
	Dust        *Store[component.DustComponent]
	Navigation  *Store[component.NavigationComponent]
	Combat      *Store[component.CombatComponent]
	Genotype    *Store[component.GenotypeComponent]
	Lightning   *Store[component.LightningComponent]
	Missile     *Store[component.MissileComponent]
	Spirit      *Store[component.SpiritComponent]
	Materialize *Store[component.MaterializeComponent]
	Drain       *Store[component.DrainComponent]
	Quasar      *Store[component.QuasarComponent]
	Swarm       *Store[component.SwarmComponent]
	Storm       *Store[component.StormComponent]
	StormCircle *Store[component.StormCircleComponent]
	Bullet      *Store[component.BulletComponent]
	Header      *Store[component.HeaderComponent]
	Member      *Store[component.MemberComponent]
	Flash       *Store[component.FlashComponent]
	Fadeout     *Store[component.FadeoutComponent]
	Splash      *Store[component.SplashComponent]
	Marker      *Store[component.MarkerComponent]
	Environment *Store[component.EnvironmentComponent]
	Death       *Store[component.DeathComponent]
	Timer       *Store[component.TimerComponent]
}

// initComponents creates all component stores
// Called once from NewWorld()
func initComponents(w *World) {
	w.Components.Glyph = NewStore[component.GlyphComponent]()
	w.Components.Sigil = NewStore[component.SigilComponent]()
	w.Components.Nugget = NewStore[component.NuggetComponent]()
	w.Components.Cursor = NewStore[component.CursorComponent]()
	w.Components.Protection = NewStore[component.ProtectionComponent]()
	w.Components.Kinetic = NewStore[component.KineticComponent]()
	w.Components.Wall = NewStore[component.WallComponent]()
	w.Components.Loot = NewStore[component.LootComponent]()
	w.Components.Energy = NewStore[component.EnergyComponent]()
	w.Components.Heat = NewStore[component.HeatComponent]()
	w.Components.Shield = NewStore[component.ShieldComponent]()
	w.Components.Boost = NewStore[component.BoostComponent]()
	w.Components.Weapon = NewStore[component.WeaponComponent]()
	w.Components.Orb = NewStore[component.OrbComponent]()
	w.Components.Ping = NewStore[component.PingComponent]()
	w.Components.Decay = NewStore[component.DecayComponent]()
	w.Components.Blossom = NewStore[component.BlossomComponent]()
	w.Components.Cleaner = NewStore[component.CleanerComponent]()
	w.Components.Dust = NewStore[component.DustComponent]()
	w.Components.Navigation = NewStore[component.NavigationComponent]()
	w.Components.Combat = NewStore[component.CombatComponent]()
	w.Components.Genotype = NewStore[component.GenotypeComponent]()
	w.Components.Lightning = NewStore[component.LightningComponent]()
	w.Components.Missile = NewStore[component.MissileComponent]()
	w.Components.Spirit = NewStore[component.SpiritComponent]()
	w.Components.Materialize = NewStore[component.MaterializeComponent]()
	w.Components.Drain = NewStore[component.DrainComponent]()
	w.Components.Quasar = NewStore[component.QuasarComponent]()
	w.Components.Swarm = NewStore[component.SwarmComponent]()
	w.Components.Storm = NewStore[component.StormComponent]()
	w.Components.StormCircle = NewStore[component.StormCircleComponent]()
	w.Components.Bullet = NewStore[component.BulletComponent]()
	w.Components.Header = NewStore[component.HeaderComponent]()
	w.Components.Member = NewStore[component.MemberComponent]()
	w.Components.Flash = NewStore[component.FlashComponent]()
	w.Components.Fadeout = NewStore[component.FadeoutComponent]()
	w.Components.Splash = NewStore[component.SplashComponent]()
	w.Components.Marker = NewStore[component.MarkerComponent]()
	w.Components.Environment = NewStore[component.EnvironmentComponent]()
	w.Components.Death = NewStore[component.DeathComponent]()
	w.Components.Timer = NewStore[component.TimerComponent]()
	w.Positions = NewPosition()
	w.Positions.SetWorld(w)
}

// removeEntity removes entity from every component store
func (w *World) removeEntity(e core.Entity) {
	w.Components.Glyph.RemoveEntity(e)
	w.Components.Sigil.RemoveEntity(e)
	w.Components.Nugget.RemoveEntity(e)
	w.Components.Cursor.RemoveEntity(e)
	w.Components.Protection.RemoveEntity(e)
	w.Components.Kinetic.RemoveEntity(e)
	w.Components.Wall.RemoveEntity(e)
	w.Components.Loot.RemoveEntity(e)
	w.Components.Energy.RemoveEntity(e)
	w.Components.Heat.RemoveEntity(e)
	w.Components.Shield.RemoveEntity(e)
	w.Components.Boost.RemoveEntity(e)
	w.Components.Weapon.RemoveEntity(e)
	w.Components.Orb.RemoveEntity(e)
	w.Components.Ping.RemoveEntity(e)
	w.Components.Decay.RemoveEntity(e)
	w.Components.Blossom.RemoveEntity(e)
	w.Components.Cleaner.RemoveEntity(e)
	w.Components.Dust.RemoveEntity(e)
	w.Components.Navigation.RemoveEntity(e)
	w.Components.Combat.RemoveEntity(e)
	w.Components.Genotype.RemoveEntity(e)
	w.Components.Lightning.RemoveEntity(e)
	w.Components.Missile.RemoveEntity(e)
	w.Components.Spirit.RemoveEntity(e)
	w.Components.Materialize.RemoveEntity(e)
	w.Components.Drain.RemoveEntity(e)
	w.Components.Quasar.RemoveEntity(e)
	w.Components.Swarm.RemoveEntity(e)
	w.Components.Storm.RemoveEntity(e)
	w.Components.StormCircle.RemoveEntity(e)
	w.Components.Bullet.RemoveEntity(e)
	w.Components.Header.RemoveEntity(e)
	w.Components.Member.RemoveEntity(e)
	w.Components.Flash.RemoveEntity(e)
	w.Components.Fadeout.RemoveEntity(e)
	w.Components.Splash.RemoveEntity(e)
	w.Components.Marker.RemoveEntity(e)
	w.Components.Environment.RemoveEntity(e)
	w.Components.Death.RemoveEntity(e)
	w.Components.Timer.RemoveEntity(e)
	w.Positions.RemoveEntity(e)
}

// removeEntitiesBatch removes entities from all stores using batch operations
func (w *World) removeEntitiesBatch(entities []core.Entity) {
	w.Components.Glyph.RemoveBatch(entities)
	w.Components.Sigil.RemoveBatch(entities)
	w.Components.Nugget.RemoveBatch(entities)
	w.Components.Cursor.RemoveBatch(entities)
	w.Components.Protection.RemoveBatch(entities)
	w.Components.Kinetic.RemoveBatch(entities)
	w.Components.Wall.RemoveBatch(entities)
	w.Components.Loot.RemoveBatch(entities)
	w.Components.Energy.RemoveBatch(entities)
	w.Components.Heat.RemoveBatch(entities)
	w.Components.Shield.RemoveBatch(entities)
	w.Components.Boost.RemoveBatch(entities)
	w.Components.Weapon.RemoveBatch(entities)
	w.Components.Orb.RemoveBatch(entities)
	w.Components.Ping.RemoveBatch(entities)
	w.Components.Decay.RemoveBatch(entities)
	w.Components.Blossom.RemoveBatch(entities)
	w.Components.Cleaner.RemoveBatch(entities)
	w.Components.Dust.RemoveBatch(entities)
	w.Components.Navigation.RemoveBatch(entities)
	w.Components.Combat.RemoveBatch(entities)
	w.Components.Genotype.RemoveBatch(entities)
	w.Components.Lightning.RemoveBatch(entities)
	w.Components.Missile.RemoveBatch(entities)
	w.Components.Spirit.RemoveBatch(entities)
	w.Components.Materialize.RemoveBatch(entities)
	w.Components.Drain.RemoveBatch(entities)
	w.Components.Quasar.RemoveBatch(entities)
	w.Components.Swarm.RemoveBatch(entities)
	w.Components.Storm.RemoveBatch(entities)
	w.Components.StormCircle.RemoveBatch(entities)
	w.Components.Bullet.RemoveBatch(entities)
	w.Components.Header.RemoveBatch(entities)
	w.Components.Member.RemoveBatch(entities)
	w.Components.Flash.RemoveBatch(entities)
	w.Components.Fadeout.RemoveBatch(entities)
	w.Components.Splash.RemoveBatch(entities)
	w.Components.Marker.RemoveBatch(entities)
	w.Components.Environment.RemoveBatch(entities)
	w.Components.Death.RemoveBatch(entities)
	w.Components.Timer.RemoveBatch(entities)
	w.Positions.RemoveBatch(entities)
}

// wipeAll clears all component stores
func (w *World) wipeAll() {
	w.Components.Glyph.ClearAllComponents()
	w.Components.Sigil.ClearAllComponents()
	w.Components.Nugget.ClearAllComponents()
	w.Components.Cursor.ClearAllComponents()
	w.Components.Protection.ClearAllComponents()
	w.Components.Kinetic.ClearAllComponents()
	w.Components.Wall.ClearAllComponents()
	w.Components.Loot.ClearAllComponents()
	w.Components.Energy.ClearAllComponents()
	w.Components.Heat.ClearAllComponents()
	w.Components.Shield.ClearAllComponents()
	w.Components.Boost.ClearAllComponents()
	w.Components.Weapon.ClearAllComponents()
	w.Components.Orb.ClearAllComponents()
	w.Components.Ping.ClearAllComponents()
	w.Components.Decay.ClearAllComponents()
	w.Components.Blossom.ClearAllComponents()
	w.Components.Cleaner.ClearAllComponents()
	w.Components.Dust.ClearAllComponents()
	w.Components.Navigation.ClearAllComponents()
	w.Components.Combat.ClearAllComponents()
	w.Components.Genotype.ClearAllComponents()
	w.Components.Lightning.ClearAllComponents()
	w.Components.Missile.ClearAllComponents()
	w.Components.Spirit.ClearAllComponents()
	w.Components.Materialize.ClearAllComponents()
	w.Components.Drain.ClearAllComponents()
	w.Components.Quasar.ClearAllComponents()
	w.Components.Swarm.ClearAllComponents()
	w.Components.Storm.ClearAllComponents()
	w.Components.StormCircle.ClearAllComponents()
	w.Components.Bullet.ClearAllComponents()
	w.Components.Header.ClearAllComponents()
	w.Components.Member.ClearAllComponents()
	w.Components.Flash.ClearAllComponents()
	w.Components.Fadeout.ClearAllComponents()
	w.Components.Splash.ClearAllComponents()
	w.Components.Marker.ClearAllComponents()
	w.Components.Environment.ClearAllComponents()
	w.Components.Death.ClearAllComponents()
	w.Components.Timer.ClearAllComponents()
	w.Positions.ClearAllComponents()
}
