// Code generated by gen-manifest; DO NOT EDIT.

package engine

import (
	"github.com/lixenwraith/vi-fighter/component"
	"github.com/lixenwraith/vi-fighter/core"
)

// Component provides typed component store pointers
// Embedded in World, initialized once at world creation
type Component struct {
	Glyph        *Store[component.GlyphComponent]
	Sigil        *Store[component.SigilComponent]
	Nugget       *Store[component.NuggetComponent]
	Cursor       *Store[component.CursorComponent]
	Protection   *Store[component.ProtectionComponent]
	Kinetic      *Store[component.KineticComponent]
	Wall         *Store[component.WallComponent]
	Loot         *Store[component.LootComponent]
	Gateway      *Store[component.GatewayComponent]
	Energy       *Store[component.EnergyComponent]
	Heat         *Store[component.HeatComponent]
	Shield       *Store[component.ShieldComponent]
	Boost        *Store[component.BoostComponent]
	Weapon       *Store[component.WeaponComponent]
	Orb          *Store[component.OrbComponent]
	Ping         *Store[component.PingComponent]
	Decay        *Store[component.DecayComponent]
	Blossom      *Store[component.BlossomComponent]
	Cleaner      *Store[component.CleanerComponent]
	Dust         *Store[component.DustComponent]
	Navigation   *Store[component.NavigationComponent]
	Combat       *Store[component.CombatComponent]
	Genotype     *Store[component.GenotypeComponent]
	Lightning    *Store[component.LightningComponent]
	Missile      *Store[component.MissileComponent]
	Pulse        *Store[component.PulseComponent]
	Spirit       *Store[component.SpiritComponent]
	Materialize  *Store[component.MaterializeComponent]
	Target       *Store[component.TargetComponent]
	TargetAnchor *Store[component.TargetAnchorComponent]
	Drain        *Store[component.DrainComponent]
	Quasar       *Store[component.QuasarComponent]
	Swarm        *Store[component.SwarmComponent]
	Storm        *Store[component.StormComponent]
	StormCircle  *Store[component.StormCircleComponent]
	Bullet       *Store[component.BulletComponent]
	Pylon        *Store[component.PylonComponent]
	Snake        *Store[component.SnakeComponent]
	SnakeHead    *Store[component.SnakeHeadComponent]
	SnakeBody    *Store[component.SnakeBodyComponent]
	SnakeMember  *Store[component.SnakeMemberComponent]
	Eye          *Store[component.EyeComponent]
	Tower        *Store[component.TowerComponent]
	Header       *Store[component.HeaderComponent]
	Member       *Store[component.MemberComponent]
	Flash        *Store[component.FlashComponent]
	Fadeout      *Store[component.FadeoutComponent]
	Splash       *Store[component.SplashComponent]
	Marker       *Store[component.MarkerComponent]
	Death        *Store[component.DeathComponent]
	Timer        *Store[component.TimerComponent]
}

// initComponents creates all component stores
// Called once from NewWorld()
func initComponents(w *World) {
	w.Components.Glyph = NewStore[component.GlyphComponent]()
	w.Components.Sigil = NewStore[component.SigilComponent]()
	w.Components.Nugget = NewStore[component.NuggetComponent]()
	w.Components.Cursor = NewStore[component.CursorComponent]()
	w.Components.Protection = NewStore[component.ProtectionComponent]()
	w.Components.Kinetic = NewStore[component.KineticComponent]()
	w.Components.Wall = NewStore[component.WallComponent]()
	w.Components.Loot = NewStore[component.LootComponent]()
	w.Components.Gateway = NewStore[component.GatewayComponent]()
	w.Components.Energy = NewStore[component.EnergyComponent]()
	w.Components.Heat = NewStore[component.HeatComponent]()
	w.Components.Shield = NewStore[component.ShieldComponent]()
	w.Components.Boost = NewStore[component.BoostComponent]()
	w.Components.Weapon = NewStore[component.WeaponComponent]()
	w.Components.Orb = NewStore[component.OrbComponent]()
	w.Components.Ping = NewStore[component.PingComponent]()
	w.Components.Decay = NewStore[component.DecayComponent]()
	w.Components.Blossom = NewStore[component.BlossomComponent]()
	w.Components.Cleaner = NewStore[component.CleanerComponent]()
	w.Components.Dust = NewStore[component.DustComponent]()
	w.Components.Navigation = NewStore[component.NavigationComponent]()
	w.Components.Combat = NewStore[component.CombatComponent]()
	w.Components.Genotype = NewStore[component.GenotypeComponent]()
	w.Components.Lightning = NewStore[component.LightningComponent]()
	w.Components.Missile = NewStore[component.MissileComponent]()
	w.Components.Pulse = NewStore[component.PulseComponent]()
	w.Components.Spirit = NewStore[component.SpiritComponent]()
	w.Components.Materialize = NewStore[component.MaterializeComponent]()
	w.Components.Target = NewStore[component.TargetComponent]()
	w.Components.TargetAnchor = NewStore[component.TargetAnchorComponent]()
	w.Components.Drain = NewStore[component.DrainComponent]()
	w.Components.Quasar = NewStore[component.QuasarComponent]()
	w.Components.Swarm = NewStore[component.SwarmComponent]()
	w.Components.Storm = NewStore[component.StormComponent]()
	w.Components.StormCircle = NewStore[component.StormCircleComponent]()
	w.Components.Bullet = NewStore[component.BulletComponent]()
	w.Components.Pylon = NewStore[component.PylonComponent]()
	w.Components.Snake = NewStore[component.SnakeComponent]()
	w.Components.SnakeHead = NewStore[component.SnakeHeadComponent]()
	w.Components.SnakeBody = NewStore[component.SnakeBodyComponent]()
	w.Components.SnakeMember = NewStore[component.SnakeMemberComponent]()
	w.Components.Eye = NewStore[component.EyeComponent]()
	w.Components.Tower = NewStore[component.TowerComponent]()
	w.Components.Header = NewStore[component.HeaderComponent]()
	w.Components.Member = NewStore[component.MemberComponent]()
	w.Components.Flash = NewStore[component.FlashComponent]()
	w.Components.Fadeout = NewStore[component.FadeoutComponent]()
	w.Components.Splash = NewStore[component.SplashComponent]()
	w.Components.Marker = NewStore[component.MarkerComponent]()
	w.Components.Death = NewStore[component.DeathComponent]()
	w.Components.Timer = NewStore[component.TimerComponent]()
	w.Positions = NewPosition()
	w.Positions.SetWorld(w)
}

// removeEntity removes entity from every component store
// Caller MUST hold updateMutex
func (w *World) removeEntity(e core.Entity) {
	w.Components.Glyph.RemoveEntityUnsafe(e)
	w.Components.Sigil.RemoveEntityUnsafe(e)
	w.Components.Nugget.RemoveEntityUnsafe(e)
	w.Components.Cursor.RemoveEntityUnsafe(e)
	w.Components.Protection.RemoveEntityUnsafe(e)
	w.Components.Kinetic.RemoveEntityUnsafe(e)
	w.Components.Wall.RemoveEntityUnsafe(e)
	w.Components.Loot.RemoveEntityUnsafe(e)
	w.Components.Gateway.RemoveEntityUnsafe(e)
	w.Components.Energy.RemoveEntityUnsafe(e)
	w.Components.Heat.RemoveEntityUnsafe(e)
	w.Components.Shield.RemoveEntityUnsafe(e)
	w.Components.Boost.RemoveEntityUnsafe(e)
	w.Components.Weapon.RemoveEntityUnsafe(e)
	w.Components.Orb.RemoveEntityUnsafe(e)
	w.Components.Ping.RemoveEntityUnsafe(e)
	w.Components.Decay.RemoveEntityUnsafe(e)
	w.Components.Blossom.RemoveEntityUnsafe(e)
	w.Components.Cleaner.RemoveEntityUnsafe(e)
	w.Components.Dust.RemoveEntityUnsafe(e)
	w.Components.Navigation.RemoveEntityUnsafe(e)
	w.Components.Combat.RemoveEntityUnsafe(e)
	w.Components.Genotype.RemoveEntityUnsafe(e)
	w.Components.Lightning.RemoveEntityUnsafe(e)
	w.Components.Missile.RemoveEntityUnsafe(e)
	w.Components.Pulse.RemoveEntityUnsafe(e)
	w.Components.Spirit.RemoveEntityUnsafe(e)
	w.Components.Materialize.RemoveEntityUnsafe(e)
	w.Components.Target.RemoveEntityUnsafe(e)
	w.Components.TargetAnchor.RemoveEntityUnsafe(e)
	w.Components.Drain.RemoveEntityUnsafe(e)
	w.Components.Quasar.RemoveEntityUnsafe(e)
	w.Components.Swarm.RemoveEntityUnsafe(e)
	w.Components.Storm.RemoveEntityUnsafe(e)
	w.Components.StormCircle.RemoveEntityUnsafe(e)
	w.Components.Bullet.RemoveEntityUnsafe(e)
	w.Components.Pylon.RemoveEntityUnsafe(e)
	w.Components.Snake.RemoveEntityUnsafe(e)
	w.Components.SnakeHead.RemoveEntityUnsafe(e)
	w.Components.SnakeBody.RemoveEntityUnsafe(e)
	w.Components.SnakeMember.RemoveEntityUnsafe(e)
	w.Components.Eye.RemoveEntityUnsafe(e)
	w.Components.Tower.RemoveEntityUnsafe(e)
	w.Components.Header.RemoveEntityUnsafe(e)
	w.Components.Member.RemoveEntityUnsafe(e)
	w.Components.Flash.RemoveEntityUnsafe(e)
	w.Components.Fadeout.RemoveEntityUnsafe(e)
	w.Components.Splash.RemoveEntityUnsafe(e)
	w.Components.Marker.RemoveEntityUnsafe(e)
	w.Components.Death.RemoveEntityUnsafe(e)
	w.Components.Timer.RemoveEntityUnsafe(e)
	w.Positions.RemoveEntityUnsafe(e)
}

// removeEntitiesBatch removes entities from all stores using batch operations
// Caller MUST hold updateMutex
func (w *World) removeEntitiesBatch(entities []core.Entity) {
	w.Components.Glyph.RemoveBatchUnsafe(entities)
	w.Components.Sigil.RemoveBatchUnsafe(entities)
	w.Components.Nugget.RemoveBatchUnsafe(entities)
	w.Components.Cursor.RemoveBatchUnsafe(entities)
	w.Components.Protection.RemoveBatchUnsafe(entities)
	w.Components.Kinetic.RemoveBatchUnsafe(entities)
	w.Components.Wall.RemoveBatchUnsafe(entities)
	w.Components.Loot.RemoveBatchUnsafe(entities)
	w.Components.Gateway.RemoveBatchUnsafe(entities)
	w.Components.Energy.RemoveBatchUnsafe(entities)
	w.Components.Heat.RemoveBatchUnsafe(entities)
	w.Components.Shield.RemoveBatchUnsafe(entities)
	w.Components.Boost.RemoveBatchUnsafe(entities)
	w.Components.Weapon.RemoveBatchUnsafe(entities)
	w.Components.Orb.RemoveBatchUnsafe(entities)
	w.Components.Ping.RemoveBatchUnsafe(entities)
	w.Components.Decay.RemoveBatchUnsafe(entities)
	w.Components.Blossom.RemoveBatchUnsafe(entities)
	w.Components.Cleaner.RemoveBatchUnsafe(entities)
	w.Components.Dust.RemoveBatchUnsafe(entities)
	w.Components.Navigation.RemoveBatchUnsafe(entities)
	w.Components.Combat.RemoveBatchUnsafe(entities)
	w.Components.Genotype.RemoveBatchUnsafe(entities)
	w.Components.Lightning.RemoveBatchUnsafe(entities)
	w.Components.Missile.RemoveBatchUnsafe(entities)
	w.Components.Pulse.RemoveBatchUnsafe(entities)
	w.Components.Spirit.RemoveBatchUnsafe(entities)
	w.Components.Materialize.RemoveBatchUnsafe(entities)
	w.Components.Target.RemoveBatchUnsafe(entities)
	w.Components.TargetAnchor.RemoveBatchUnsafe(entities)
	w.Components.Drain.RemoveBatchUnsafe(entities)
	w.Components.Quasar.RemoveBatchUnsafe(entities)
	w.Components.Swarm.RemoveBatchUnsafe(entities)
	w.Components.Storm.RemoveBatchUnsafe(entities)
	w.Components.StormCircle.RemoveBatchUnsafe(entities)
	w.Components.Bullet.RemoveBatchUnsafe(entities)
	w.Components.Pylon.RemoveBatchUnsafe(entities)
	w.Components.Snake.RemoveBatchUnsafe(entities)
	w.Components.SnakeHead.RemoveBatchUnsafe(entities)
	w.Components.SnakeBody.RemoveBatchUnsafe(entities)
	w.Components.SnakeMember.RemoveBatchUnsafe(entities)
	w.Components.Eye.RemoveBatchUnsafe(entities)
	w.Components.Tower.RemoveBatchUnsafe(entities)
	w.Components.Header.RemoveBatchUnsafe(entities)
	w.Components.Member.RemoveBatchUnsafe(entities)
	w.Components.Flash.RemoveBatchUnsafe(entities)
	w.Components.Fadeout.RemoveBatchUnsafe(entities)
	w.Components.Splash.RemoveBatchUnsafe(entities)
	w.Components.Marker.RemoveBatchUnsafe(entities)
	w.Components.Death.RemoveBatchUnsafe(entities)
	w.Components.Timer.RemoveBatchUnsafe(entities)
	w.Positions.RemoveBatchUnsafe(entities)
}

// wipeAll clears all component stores
// Caller MUST hold updateMutex
func (w *World) wipeAll() {
	w.Components.Glyph.ClearAllComponentsUnsafe()
	w.Components.Sigil.ClearAllComponentsUnsafe()
	w.Components.Nugget.ClearAllComponentsUnsafe()
	w.Components.Cursor.ClearAllComponentsUnsafe()
	w.Components.Protection.ClearAllComponentsUnsafe()
	w.Components.Kinetic.ClearAllComponentsUnsafe()
	w.Components.Wall.ClearAllComponentsUnsafe()
	w.Components.Loot.ClearAllComponentsUnsafe()
	w.Components.Gateway.ClearAllComponentsUnsafe()
	w.Components.Energy.ClearAllComponentsUnsafe()
	w.Components.Heat.ClearAllComponentsUnsafe()
	w.Components.Shield.ClearAllComponentsUnsafe()
	w.Components.Boost.ClearAllComponentsUnsafe()
	w.Components.Weapon.ClearAllComponentsUnsafe()
	w.Components.Orb.ClearAllComponentsUnsafe()
	w.Components.Ping.ClearAllComponentsUnsafe()
	w.Components.Decay.ClearAllComponentsUnsafe()
	w.Components.Blossom.ClearAllComponentsUnsafe()
	w.Components.Cleaner.ClearAllComponentsUnsafe()
	w.Components.Dust.ClearAllComponentsUnsafe()
	w.Components.Navigation.ClearAllComponentsUnsafe()
	w.Components.Combat.ClearAllComponentsUnsafe()
	w.Components.Genotype.ClearAllComponentsUnsafe()
	w.Components.Lightning.ClearAllComponentsUnsafe()
	w.Components.Missile.ClearAllComponentsUnsafe()
	w.Components.Pulse.ClearAllComponentsUnsafe()
	w.Components.Spirit.ClearAllComponentsUnsafe()
	w.Components.Materialize.ClearAllComponentsUnsafe()
	w.Components.Target.ClearAllComponentsUnsafe()
	w.Components.TargetAnchor.ClearAllComponentsUnsafe()
	w.Components.Drain.ClearAllComponentsUnsafe()
	w.Components.Quasar.ClearAllComponentsUnsafe()
	w.Components.Swarm.ClearAllComponentsUnsafe()
	w.Components.Storm.ClearAllComponentsUnsafe()
	w.Components.StormCircle.ClearAllComponentsUnsafe()
	w.Components.Bullet.ClearAllComponentsUnsafe()
	w.Components.Pylon.ClearAllComponentsUnsafe()
	w.Components.Snake.ClearAllComponentsUnsafe()
	w.Components.SnakeHead.ClearAllComponentsUnsafe()
	w.Components.SnakeBody.ClearAllComponentsUnsafe()
	w.Components.SnakeMember.ClearAllComponentsUnsafe()
	w.Components.Eye.ClearAllComponentsUnsafe()
	w.Components.Tower.ClearAllComponentsUnsafe()
	w.Components.Header.ClearAllComponentsUnsafe()
	w.Components.Member.ClearAllComponentsUnsafe()
	w.Components.Flash.ClearAllComponentsUnsafe()
	w.Components.Fadeout.ClearAllComponentsUnsafe()
	w.Components.Splash.ClearAllComponentsUnsafe()
	w.Components.Marker.ClearAllComponentsUnsafe()
	w.Components.Death.ClearAllComponentsUnsafe()
	w.Components.Timer.ClearAllComponentsUnsafe()
	w.Positions.ClearAllComponentsUnsafe()
}
