// Code generated by gen-manifest; DO NOT EDIT.

//go:build vif_headless || vif_noaudio || wasm

package manifest

import (
	"github.com/lixenwraith/vif/internal/engine"
	"github.com/lixenwraith/vif/internal/system"
)

func buildAudioSystems(w *engine.World) []engine.System {
	return []engine.System{
		system.NewAudioSystem(w),
		system.NewMusicSystem(w),
	}
}

var activeAudioSystems = []string{
	"audio",
	"music",
}
