// Code generated by gen-manifest; DO NOT EDIT.

//go:build !vif_headless

package manifest

import (
	"github.com/lixenwraith/vi-fighter/internal/engine"
	"github.com/lixenwraith/vi-fighter/internal/render"
	"github.com/lixenwraith/vi-fighter/internal/render/renderer"
)

// BuildRenderers constructs every active renderer paired with its priority.
func BuildRenderers(ctx *engine.GameContext) []render.Registration {
	return []render.Registration{
		{Renderer: renderer.NewPingRenderer(ctx), Priority: render.PriorityPing},
		{Renderer: renderer.NewChargeLineRenderer(ctx), Priority: render.PriorityChargeLine},
		{Renderer: renderer.NewWallRenderer(ctx), Priority: render.PriorityWall},
		{Renderer: renderer.NewGlyphRenderer(ctx), Priority: render.PriorityGlyph},
		{Renderer: renderer.NewSigilRenderer(ctx), Priority: render.PrioritySigil},
		{Renderer: renderer.NewGoldRenderer(ctx), Priority: render.PriorityGold},
		{Renderer: renderer.NewHealthBarRenderer(ctx), Priority: render.PriorityHealthBar},
		{Renderer: renderer.NewPylonRenderer(ctx), Priority: render.PriorityPylon},
		{Renderer: renderer.NewTowerRenderer(ctx), Priority: render.PriorityTower},
		{Renderer: renderer.NewEyeRenderer(ctx), Priority: render.PriorityEye},
		{Renderer: renderer.NewSnakeRenderer(ctx), Priority: render.PrioritySnake},
		{Renderer: renderer.NewDrainRenderer(ctx), Priority: render.PriorityDrain},
		{Renderer: renderer.NewQuasarRenderer(ctx), Priority: render.PriorityQuasar},
		{Renderer: renderer.NewSwarmRenderer(ctx), Priority: render.PrioritySwarm},
		{Renderer: renderer.NewStormRenderer(ctx), Priority: render.PriorityStorm},
		{Renderer: renderer.NewCleanerRenderer(ctx), Priority: render.PriorityCleaner},
		{Renderer: renderer.NewMaterializeRenderer(ctx), Priority: render.PriorityMaterialize},
		{Renderer: renderer.NewTeleportLineRenderer(ctx), Priority: render.PriorityTeleportLine},
		{Renderer: renderer.NewShieldRenderer(ctx), Priority: render.PriorityShield},
		{Renderer: renderer.NewEmberRenderer(ctx), Priority: render.PriorityEmber},
		{Renderer: renderer.NewOrbRenderer(ctx), Priority: render.PriorityOrb},
		{Renderer: renderer.NewLightningRenderer(ctx), Priority: render.PriorityLightning},
		{Renderer: renderer.NewMissileRenderer(ctx), Priority: render.PriorityMissile},
		{Renderer: renderer.NewPulseRenderer(ctx), Priority: render.PriorityPulse},
		{Renderer: renderer.NewBulletRenderer(ctx), Priority: render.PriorityBullet},
		{Renderer: renderer.NewFlashRenderer(ctx), Priority: render.PriorityFlash},
		{Renderer: renderer.NewFadeoutRenderer(ctx), Priority: render.PriorityFadeout},
		{Renderer: renderer.NewExplosionRenderer(ctx), Priority: render.PriorityExplosion},
		{Renderer: renderer.NewSpiritRenderer(ctx), Priority: render.PrioritySpirit},
		{Renderer: renderer.NewSplashRenderer(ctx), Priority: render.PrioritySplash},
		{Renderer: renderer.NewMarkerRenderer(ctx), Priority: render.PriorityMarker},
		{Renderer: renderer.NewGrayoutRenderer(ctx), Priority: render.PriorityGrayout},
		{Renderer: renderer.NewStrobeRenderer(ctx), Priority: render.PriorityStrobe},
		{Renderer: renderer.NewDimRenderer(ctx), Priority: render.PriorityDim},
		{Renderer: renderer.NewHeatRenderer(ctx), Priority: render.PriorityHeat},
		{Renderer: renderer.NewIndicatorRenderer(ctx), Priority: render.PriorityIndicator},
		{Renderer: renderer.NewStatusBarRenderer(ctx), Priority: render.PriorityStatusBar},
		{Renderer: renderer.NewPeerCursorRenderer(ctx), Priority: render.PriorityPeerCursor},
		{Renderer: renderer.NewCursorRenderer(ctx), Priority: render.PriorityCursor},
		{Renderer: renderer.NewFlowFieldDebugRenderer(ctx), Priority: render.PriorityFlowField},
		{Renderer: renderer.NewPinnedStatsRenderer(ctx), Priority: render.PriorityPinnedState},
		{Renderer: renderer.NewOverlayRenderer(ctx), Priority: render.PriorityOverlay},
	}
}
