// Code generated by gen-manifest; DO NOT EDIT.

package engine

import (
	"slices"

	"github.com/lixenwraith/vi-fighter/internal/component"
	"github.com/lixenwraith/vi-fighter/internal/core"
)

// StoreEntry is one entity's component in a capture. The reference is a
// core.Entity, never a dense index: dense positions are an artifact of insertion
// order on the instance that produced them and mean nothing on any other.
type StoreEntry[T any] struct {
	Entity core.Entity `json:"e"`
	Value  T           `json:"v"`
}

// SharedWorldState is every shared-domain component in the world, by store, plus
// the placements and the allocator counters. Player-domain entities are excluded
// at capture: a snapshot describes the shared world and nothing else (D-1, D-6),
// and a participant's own simulation does not exist on any other instance (D-2).
type SharedWorldState struct {
	// NextEntity is the shared allocator's next ID. It travels because entity
	// identity is shared state: an installed world that allocated from a different
	// counter would give the next spawned entity an ID the sender used for
	// something else.
	NextEntity uint64 `json:"next_entity"`

	// Created and Destroyed are the shared domain's lifetime counters. They are in
	// the compared surface, because two participants creating and destroying the
	// same shared entities must agree on how many there have been; an installed
	// world reporting its own totals disagrees from the tick it arrives.
	Created   int64 `json:"created"`
	Destroyed int64 `json:"destroyed"`

	Positions    []StoreEntry[component.PositionComponent]     `json:"positions,omitempty"`
	Glyph        []StoreEntry[component.GlyphComponent]        `json:"glyph,omitempty"`
	Sigil        []StoreEntry[component.SigilComponent]        `json:"sigil,omitempty"`
	Nugget       []StoreEntry[component.NuggetComponent]       `json:"nugget,omitempty"`
	Cursor       []StoreEntry[component.CursorComponent]       `json:"cursor,omitempty"`
	Protection   []StoreEntry[component.ProtectionComponent]   `json:"protection,omitempty"`
	Kinetic      []StoreEntry[component.KineticComponent]      `json:"kinetic,omitempty"`
	Wall         []StoreEntry[component.WallComponent]         `json:"wall,omitempty"`
	Loot         []StoreEntry[component.LootComponent]         `json:"loot,omitempty"`
	Gateway      []StoreEntry[component.GatewayComponent]      `json:"gateway,omitempty"`
	Energy       []StoreEntry[component.EnergyComponent]       `json:"energy,omitempty"`
	Heat         []StoreEntry[component.HeatComponent]         `json:"heat,omitempty"`
	Shield       []StoreEntry[component.ShieldComponent]       `json:"shield,omitempty"`
	Boost        []StoreEntry[component.BoostComponent]        `json:"boost,omitempty"`
	Weapon       []StoreEntry[component.WeaponComponent]       `json:"weapon,omitempty"`
	Orb          []StoreEntry[component.OrbComponent]          `json:"orb,omitempty"`
	Ping         []StoreEntry[component.PingComponent]         `json:"ping,omitempty"`
	CursorView   []StoreEntry[component.CursorViewComponent]   `json:"cursorview,omitempty"`
	Decay        []StoreEntry[component.DecayComponent]        `json:"decay,omitempty"`
	Blossom      []StoreEntry[component.BlossomComponent]      `json:"blossom,omitempty"`
	Cleaner      []StoreEntry[component.CleanerComponent]      `json:"cleaner,omitempty"`
	Dust         []StoreEntry[component.DustComponent]         `json:"dust,omitempty"`
	Navigation   []StoreEntry[component.NavigationComponent]   `json:"navigation,omitempty"`
	Combat       []StoreEntry[component.CombatComponent]       `json:"combat,omitempty"`
	Genotype     []StoreEntry[component.GenotypeComponent]     `json:"genotype,omitempty"`
	Lightning    []StoreEntry[component.LightningComponent]    `json:"lightning,omitempty"`
	Missile      []StoreEntry[component.MissileComponent]      `json:"missile,omitempty"`
	Pulse        []StoreEntry[component.PulseComponent]        `json:"pulse,omitempty"`
	Spirit       []StoreEntry[component.SpiritComponent]       `json:"spirit,omitempty"`
	Materialize  []StoreEntry[component.MaterializeComponent]  `json:"materialize,omitempty"`
	Target       []StoreEntry[component.TargetComponent]       `json:"target,omitempty"`
	TargetAnchor []StoreEntry[component.TargetAnchorComponent] `json:"targetanchor,omitempty"`
	Drain        []StoreEntry[component.DrainComponent]        `json:"drain,omitempty"`
	Quasar       []StoreEntry[component.QuasarComponent]       `json:"quasar,omitempty"`
	Swarm        []StoreEntry[component.SwarmComponent]        `json:"swarm,omitempty"`
	Storm        []StoreEntry[component.StormComponent]        `json:"storm,omitempty"`
	StormCircle  []StoreEntry[component.StormCircleComponent]  `json:"stormcircle,omitempty"`
	Bullet       []StoreEntry[component.BulletComponent]       `json:"bullet,omitempty"`
	Pylon        []StoreEntry[component.PylonComponent]        `json:"pylon,omitempty"`
	Snake        []StoreEntry[component.SnakeComponent]        `json:"snake,omitempty"`
	SnakeHead    []StoreEntry[component.SnakeHeadComponent]    `json:"snakehead,omitempty"`
	SnakeBody    []StoreEntry[component.SnakeBodyComponent]    `json:"snakebody,omitempty"`
	SnakeMember  []StoreEntry[component.SnakeMemberComponent]  `json:"snakemember,omitempty"`
	Eye          []StoreEntry[component.EyeComponent]          `json:"eye,omitempty"`
	Tower        []StoreEntry[component.TowerComponent]        `json:"tower,omitempty"`
	Header       []StoreEntry[component.HeaderComponent]       `json:"header,omitempty"`
	Member       []StoreEntry[component.MemberComponent]       `json:"member,omitempty"`
	Flash        []StoreEntry[component.FlashComponent]        `json:"flash,omitempty"`
	Fadeout      []StoreEntry[component.FadeoutComponent]      `json:"fadeout,omitempty"`
	Splash       []StoreEntry[component.SplashComponent]       `json:"splash,omitempty"`
	Marker       []StoreEntry[component.MarkerComponent]       `json:"marker,omitempty"`
	Death        []StoreEntry[component.DeathComponent]        `json:"death,omitempty"`
	Timer        []StoreEntry[component.TimerComponent]        `json:"timer,omitempty"`
}

// CaptureSharedWorld reads every shared entity's components into a transferable
// value. Entities are emitted in store order, which is the order the receiving
// instance re-inserts them in, so a capture of an installed world equals the
// capture it was installed from.
//
// Caller MUST hold updateMutex: this reads every store.
func (w *World) CaptureSharedWorld() SharedWorldState {
	var s SharedWorldState
	s.NextEntity = w.nextEntityID[core.DomainShared]
	s.Created = w.createdCount[core.DomainShared].Load()
	s.Destroyed = w.destroyedCount[core.DomainShared].Load()

	for _, e := range w.Positions.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Positions.GetPosition(e); ok {
			s.Positions = append(s.Positions, StoreEntry[component.PositionComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Glyph.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Glyph.GetComponent(e); ok {
			s.Glyph = append(s.Glyph, StoreEntry[component.GlyphComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Sigil.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Sigil.GetComponent(e); ok {
			s.Sigil = append(s.Sigil, StoreEntry[component.SigilComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Nugget.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Nugget.GetComponent(e); ok {
			s.Nugget = append(s.Nugget, StoreEntry[component.NuggetComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Cursor.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Cursor.GetComponent(e); ok {
			s.Cursor = append(s.Cursor, StoreEntry[component.CursorComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Protection.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Protection.GetComponent(e); ok {
			s.Protection = append(s.Protection, StoreEntry[component.ProtectionComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Kinetic.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Kinetic.GetComponent(e); ok {
			s.Kinetic = append(s.Kinetic, StoreEntry[component.KineticComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Wall.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Wall.GetComponent(e); ok {
			s.Wall = append(s.Wall, StoreEntry[component.WallComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Loot.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Loot.GetComponent(e); ok {
			s.Loot = append(s.Loot, StoreEntry[component.LootComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Gateway.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Gateway.GetComponent(e); ok {
			s.Gateway = append(s.Gateway, StoreEntry[component.GatewayComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Energy.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Energy.GetComponent(e); ok {
			s.Energy = append(s.Energy, StoreEntry[component.EnergyComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Heat.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Heat.GetComponent(e); ok {
			s.Heat = append(s.Heat, StoreEntry[component.HeatComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Shield.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Shield.GetComponent(e); ok {
			s.Shield = append(s.Shield, StoreEntry[component.ShieldComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Boost.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Boost.GetComponent(e); ok {
			s.Boost = append(s.Boost, StoreEntry[component.BoostComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Weapon.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Weapon.GetComponent(e); ok {
			s.Weapon = append(s.Weapon, StoreEntry[component.WeaponComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Orb.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Orb.GetComponent(e); ok {
			s.Orb = append(s.Orb, StoreEntry[component.OrbComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Ping.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Ping.GetComponent(e); ok {
			s.Ping = append(s.Ping, StoreEntry[component.PingComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.CursorView.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.CursorView.GetComponent(e); ok {
			s.CursorView = append(s.CursorView, StoreEntry[component.CursorViewComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Decay.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Decay.GetComponent(e); ok {
			s.Decay = append(s.Decay, StoreEntry[component.DecayComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Blossom.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Blossom.GetComponent(e); ok {
			s.Blossom = append(s.Blossom, StoreEntry[component.BlossomComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Cleaner.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Cleaner.GetComponent(e); ok {
			s.Cleaner = append(s.Cleaner, StoreEntry[component.CleanerComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Dust.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Dust.GetComponent(e); ok {
			s.Dust = append(s.Dust, StoreEntry[component.DustComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Navigation.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Navigation.GetComponent(e); ok {
			s.Navigation = append(s.Navigation, StoreEntry[component.NavigationComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Combat.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Combat.GetComponent(e); ok {
			s.Combat = append(s.Combat, StoreEntry[component.CombatComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Genotype.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Genotype.GetComponent(e); ok {
			s.Genotype = append(s.Genotype, StoreEntry[component.GenotypeComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Lightning.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Lightning.GetComponent(e); ok {
			s.Lightning = append(s.Lightning, StoreEntry[component.LightningComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Missile.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Missile.GetComponent(e); ok {
			s.Missile = append(s.Missile, StoreEntry[component.MissileComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Pulse.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Pulse.GetComponent(e); ok {
			s.Pulse = append(s.Pulse, StoreEntry[component.PulseComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Spirit.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Spirit.GetComponent(e); ok {
			s.Spirit = append(s.Spirit, StoreEntry[component.SpiritComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Materialize.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Materialize.GetComponent(e); ok {
			s.Materialize = append(s.Materialize, StoreEntry[component.MaterializeComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Target.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Target.GetComponent(e); ok {
			s.Target = append(s.Target, StoreEntry[component.TargetComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.TargetAnchor.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.TargetAnchor.GetComponent(e); ok {
			s.TargetAnchor = append(s.TargetAnchor, StoreEntry[component.TargetAnchorComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Drain.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Drain.GetComponent(e); ok {
			s.Drain = append(s.Drain, StoreEntry[component.DrainComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Quasar.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Quasar.GetComponent(e); ok {
			s.Quasar = append(s.Quasar, StoreEntry[component.QuasarComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Swarm.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Swarm.GetComponent(e); ok {
			s.Swarm = append(s.Swarm, StoreEntry[component.SwarmComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Storm.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Storm.GetComponent(e); ok {
			s.Storm = append(s.Storm, StoreEntry[component.StormComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.StormCircle.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.StormCircle.GetComponent(e); ok {
			s.StormCircle = append(s.StormCircle, StoreEntry[component.StormCircleComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Bullet.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Bullet.GetComponent(e); ok {
			s.Bullet = append(s.Bullet, StoreEntry[component.BulletComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Pylon.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Pylon.GetComponent(e); ok {
			s.Pylon = append(s.Pylon, StoreEntry[component.PylonComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Snake.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Snake.GetComponent(e); ok {
			s.Snake = append(s.Snake, StoreEntry[component.SnakeComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.SnakeHead.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.SnakeHead.GetComponent(e); ok {
			s.SnakeHead = append(s.SnakeHead, StoreEntry[component.SnakeHeadComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.SnakeBody.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.SnakeBody.GetComponent(e); ok {
			s.SnakeBody = append(s.SnakeBody, StoreEntry[component.SnakeBodyComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.SnakeMember.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.SnakeMember.GetComponent(e); ok {
			s.SnakeMember = append(s.SnakeMember, StoreEntry[component.SnakeMemberComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Eye.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Eye.GetComponent(e); ok {
			s.Eye = append(s.Eye, StoreEntry[component.EyeComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Tower.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Tower.GetComponent(e); ok {
			s.Tower = append(s.Tower, StoreEntry[component.TowerComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Header.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Header.GetComponent(e); ok {
			s.Header = append(s.Header, StoreEntry[component.HeaderComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Member.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Member.GetComponent(e); ok {
			s.Member = append(s.Member, StoreEntry[component.MemberComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Flash.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Flash.GetComponent(e); ok {
			s.Flash = append(s.Flash, StoreEntry[component.FlashComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Fadeout.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Fadeout.GetComponent(e); ok {
			s.Fadeout = append(s.Fadeout, StoreEntry[component.FadeoutComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Splash.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Splash.GetComponent(e); ok {
			s.Splash = append(s.Splash, StoreEntry[component.SplashComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Marker.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Marker.GetComponent(e); ok {
			s.Marker = append(s.Marker, StoreEntry[component.MarkerComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Death.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Death.GetComponent(e); ok {
			s.Death = append(s.Death, StoreEntry[component.DeathComponent]{Entity: e, Value: v})
		}
	}
	for _, e := range w.Components.Timer.Entities() {
		if e.Domain() != core.DomainShared {
			continue
		}
		if v, ok := w.Components.Timer.GetComponent(e); ok {
			s.Timer = append(s.Timer, StoreEntry[component.TimerComponent]{Entity: e, Value: v})
		}
	}
	return s
}

// InstallSharedWorld replaces this world's shared half with a capture. Player
// entities are left untouched: they are this instance's own and no capture
// describes them.
//
// Caller MUST hold updateMutex.
func (w *World) InstallSharedWorld(s SharedWorldState) {
	w.clearSharedEntities()

	for _, en := range s.Positions {
		w.Positions.SetPosition(en.Entity, en.Value)
	}
	for _, en := range s.Glyph {
		w.Components.Glyph.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Sigil {
		w.Components.Sigil.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Nugget {
		w.Components.Nugget.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Cursor {
		w.Components.Cursor.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Protection {
		w.Components.Protection.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Kinetic {
		w.Components.Kinetic.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Wall {
		w.Components.Wall.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Loot {
		w.Components.Loot.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Gateway {
		w.Components.Gateway.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Energy {
		w.Components.Energy.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Heat {
		w.Components.Heat.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Shield {
		w.Components.Shield.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Boost {
		w.Components.Boost.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Weapon {
		w.Components.Weapon.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Orb {
		w.Components.Orb.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Ping {
		w.Components.Ping.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.CursorView {
		w.Components.CursorView.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Decay {
		w.Components.Decay.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Blossom {
		w.Components.Blossom.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Cleaner {
		w.Components.Cleaner.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Dust {
		w.Components.Dust.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Navigation {
		w.Components.Navigation.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Combat {
		w.Components.Combat.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Genotype {
		w.Components.Genotype.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Lightning {
		w.Components.Lightning.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Missile {
		w.Components.Missile.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Pulse {
		w.Components.Pulse.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Spirit {
		w.Components.Spirit.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Materialize {
		w.Components.Materialize.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Target {
		w.Components.Target.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.TargetAnchor {
		w.Components.TargetAnchor.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Drain {
		w.Components.Drain.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Quasar {
		w.Components.Quasar.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Swarm {
		w.Components.Swarm.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Storm {
		w.Components.Storm.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.StormCircle {
		w.Components.StormCircle.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Bullet {
		w.Components.Bullet.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Pylon {
		w.Components.Pylon.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Snake {
		w.Components.Snake.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.SnakeHead {
		w.Components.SnakeHead.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.SnakeBody {
		w.Components.SnakeBody.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.SnakeMember {
		w.Components.SnakeMember.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Eye {
		w.Components.Eye.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Tower {
		w.Components.Tower.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Header {
		w.Components.Header.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Member {
		w.Components.Member.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Flash {
		w.Components.Flash.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Fadeout {
		w.Components.Fadeout.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Splash {
		w.Components.Splash.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Marker {
		w.Components.Marker.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Death {
		w.Components.Death.SetComponent(en.Entity, en.Value)
	}
	for _, en := range s.Timer {
		w.Components.Timer.SetComponent(en.Entity, en.Value)
	}
	if s.NextEntity > 0 {
		w.nextEntityID[core.DomainShared] = s.NextEntity
	}
	w.createdCount[core.DomainShared].Store(s.Created)
	w.destroyedCount[core.DomainShared].Store(s.Destroyed)

	// The spatial index is derived, not shipped: SetPosition above rebuilt it.
	// Its gauges are published on the status cadence, so republish them here —
	// they describe what was just installed, and they are in the compared surface.
	w.Positions.PublishTelemetry()
}

// clearSharedEntities removes every shared entity from every store, so an install
// replaces the shared world rather than merging into it. Merging would leave
// entities this instance had derived on its own beside the capture's, which is
// the divergence an install exists to end.
//
// Caller MUST hold updateMutex.
func (w *World) clearSharedEntities() {
	shared := make([]core.Entity, 0, len(w.componentMask))
	for e := range w.componentMask {
		if e.Domain() == core.DomainShared {
			shared = append(shared, e)
		}
	}
	// Sorted before removal: the stores are dense with swap-back removal, so the
	// order entities leave in decides where the player entities that stay end up.
	// That layout is not compared, but an install must not be one of the places a
	// map's iteration order reaches the world.
	slices.Sort(shared)
	for _, e := range shared {
		w.removeEntity(e)
	}
}
