// Code generated by gen-manifest; DO NOT EDIT.

package manifest

import (
	"github.com/lixenwraith/vi-fighter/engine"
	"github.com/lixenwraith/vi-fighter/registry"
	"github.com/lixenwraith/vi-fighter/render"
	"github.com/lixenwraith/vi-fighter/render/renderer"
	"github.com/lixenwraith/vi-fighter/system"
)

// RegisterSystems registers all system factories with the registry
func RegisterSystems() {
	registry.RegisterSystem("ping", func(w any) any {
		return system.NewPingSystem(w.(*engine.World))
	})
	registry.RegisterSystem("transient", func(w any) any {
		return system.NewTransientSystem(w.(*engine.World))
	})
	registry.RegisterSystem("camera", func(w any) any {
		return system.NewCameraSystem(w.(*engine.World))
	})
	registry.RegisterSystem("energy", func(w any) any {
		return system.NewEnergySystem(w.(*engine.World))
	})
	registry.RegisterSystem("shield", func(w any) any {
		return system.NewShieldSystem(w.(*engine.World))
	})
	registry.RegisterSystem("heat", func(w any) any {
		return system.NewHeatSystem(w.(*engine.World))
	})
	registry.RegisterSystem("boost", func(w any) any {
		return system.NewBoostSystem(w.(*engine.World))
	})
	registry.RegisterSystem("weapon", func(w any) any {
		return system.NewWeaponSystem(w.(*engine.World))
	})
	registry.RegisterSystem("typing", func(w any) any {
		return system.NewTypingSystem(w.(*engine.World))
	})
	registry.RegisterSystem("composite", func(w any) any {
		return system.NewCompositeSystem(w.(*engine.World))
	})
	registry.RegisterSystem("wall", func(w any) any {
		return system.NewWallSystem(w.(*engine.World))
	})
	registry.RegisterSystem("tower", func(w any) any {
		return system.NewTowerSystem(w.(*engine.World))
	})
	registry.RegisterSystem("gateway", func(w any) any {
		return system.NewGatewaySystem(w.(*engine.World))
	})
	registry.RegisterSystem("loot", func(w any) any {
		return system.NewLootSystem(w.(*engine.World))
	})
	registry.RegisterSystem("glyph", func(w any) any {
		return system.NewGlyphSystem(w.(*engine.World))
	})
	registry.RegisterSystem("nugget", func(w any) any {
		return system.NewNuggetSystem(w.(*engine.World))
	})
	registry.RegisterSystem("decay", func(w any) any {
		return system.NewDecaySystem(w.(*engine.World))
	})
	registry.RegisterSystem("blossom", func(w any) any {
		return system.NewBlossomSystem(w.(*engine.World))
	})
	registry.RegisterSystem("gold", func(w any) any {
		return system.NewGoldSystem(w.(*engine.World))
	})
	registry.RegisterSystem("materialize", func(w any) any {
		return system.NewMaterializeSystem(w.(*engine.World))
	})
	registry.RegisterSystem("cleaner", func(w any) any {
		return system.NewCleanerSystem(w.(*engine.World))
	})
	registry.RegisterSystem("fuse", func(w any) any {
		return system.NewFuseSystem(w.(*engine.World))
	})
	registry.RegisterSystem("spirit", func(w any) any {
		return system.NewSpiritSystem(w.(*engine.World))
	})
	registry.RegisterSystem("lightning", func(w any) any {
		return system.NewLightningSystem(w.(*engine.World))
	})
	registry.RegisterSystem("missile", func(w any) any {
		return system.NewMissileSystem(w.(*engine.World))
	})
	registry.RegisterSystem("navigation", func(w any) any {
		return system.NewNavigationSystem(w.(*engine.World))
	})
	registry.RegisterSystem("soft_collision", func(w any) any {
		return system.NewSoftCollisionSystem(w.(*engine.World))
	})
	registry.RegisterSystem("combat", func(w any) any {
		return system.NewCombatSystem(w.(*engine.World))
	})
	registry.RegisterSystem("drain", func(w any) any {
		return system.NewDrainSystem(w.(*engine.World))
	})
	registry.RegisterSystem("quasar", func(w any) any {
		return system.NewQuasarSystem(w.(*engine.World))
	})
	registry.RegisterSystem("swarm", func(w any) any {
		return system.NewSwarmSystem(w.(*engine.World))
	})
	registry.RegisterSystem("storm", func(w any) any {
		return system.NewStormSystem(w.(*engine.World))
	})
	registry.RegisterSystem("pylon", func(w any) any {
		return system.NewPylonSystem(w.(*engine.World))
	})
	registry.RegisterSystem("snake", func(w any) any {
		return system.NewSnakeSystem(w.(*engine.World))
	})
	registry.RegisterSystem("eye", func(w any) any {
		return system.NewEyeSystem(w.(*engine.World))
	})
	registry.RegisterSystem("bullet", func(w any) any {
		return system.NewBulletSystem(w.(*engine.World))
	})
	registry.RegisterSystem("dust", func(w any) any {
		return system.NewDustSystem(w.(*engine.World))
	})
	registry.RegisterSystem("flash", func(w any) any {
		return system.NewFlashSystem(w.(*engine.World))
	})
	registry.RegisterSystem("fadeout", func(w any) any {
		return system.NewFadeoutSystem(w.(*engine.World))
	})
	registry.RegisterSystem("marker", func(w any) any {
		return system.NewMarkerSystem(w.(*engine.World))
	})
	registry.RegisterSystem("explosion", func(w any) any {
		return system.NewExplosionSystem(w.(*engine.World))
	})
	registry.RegisterSystem("motion_marker", func(w any) any {
		return system.NewMotionMarkerSystem(w.(*engine.World))
	})
	registry.RegisterSystem("splash", func(w any) any {
		return system.NewSplashSystem(w.(*engine.World))
	})
	registry.RegisterSystem("environment", func(w any) any {
		return system.NewEnvironmentSystem(w.(*engine.World))
	})
	registry.RegisterSystem("death", func(w any) any {
		return system.NewDeathSystem(w.(*engine.World))
	})
	registry.RegisterSystem("timekeeper", func(w any) any {
		return system.NewTimeKeeperSystem(w.(*engine.World))
	})
	registry.RegisterSystem("adaptation", func(w any) any {
		return system.NewAdaptationSystem(w.(*engine.World))
	})
	registry.RegisterSystem("genetic", func(w any) any {
		return system.NewGeneticSystem(w.(*engine.World))
	})
	registry.RegisterSystem("audio", func(w any) any {
		return system.NewAudioSystem(w.(*engine.World))
	})
	registry.RegisterSystem("music", func(w any) any {
		return system.NewMusicSystem(w.(*engine.World))
	})
	registry.RegisterSystem("diag", func(w any) any {
		return system.NewDiagSystem(w.(*engine.World))
	})
}

// RegisterRenderers registers all renderer factories with priorities
func RegisterRenderers() {
	registry.RegisterRenderer("ping", func(ctx any) any {
		return renderer.NewPingRenderer(ctx.(*engine.GameContext))
	}, render.PriorityPing)
	registry.RegisterRenderer("chargeline", func(ctx any) any {
		return renderer.NewChargeLineRenderer(ctx.(*engine.GameContext))
	}, render.PriorityChargeLine)
	registry.RegisterRenderer("wall", func(ctx any) any {
		return renderer.NewWallRenderer(ctx.(*engine.GameContext))
	}, render.PriorityWall)
	registry.RegisterRenderer("glyph", func(ctx any) any {
		return renderer.NewGlyphRenderer(ctx.(*engine.GameContext))
	}, render.PriorityGlyph)
	registry.RegisterRenderer("sigil", func(ctx any) any {
		return renderer.NewSigilRenderer(ctx.(*engine.GameContext))
	}, render.PrioritySigil)
	registry.RegisterRenderer("gold", func(ctx any) any {
		return renderer.NewGoldRenderer(ctx.(*engine.GameContext))
	}, render.PriorityGold)
	registry.RegisterRenderer("healthbar", func(ctx any) any {
		return renderer.NewHealthBarRenderer(ctx.(*engine.GameContext))
	}, render.PriorityHealthBar)
	registry.RegisterRenderer("pylon", func(ctx any) any {
		return renderer.NewPylonRenderer(ctx.(*engine.GameContext))
	}, render.PriorityPylon)
	registry.RegisterRenderer("tower", func(ctx any) any {
		return renderer.NewTowerRenderer(ctx.(*engine.GameContext))
	}, render.PriorityTower)
	registry.RegisterRenderer("eye", func(ctx any) any {
		return renderer.NewEyeRenderer(ctx.(*engine.GameContext))
	}, render.PriorityEye)
	registry.RegisterRenderer("snake", func(ctx any) any {
		return renderer.NewSnakeRenderer(ctx.(*engine.GameContext))
	}, render.PrioritySnake)
	registry.RegisterRenderer("drain", func(ctx any) any {
		return renderer.NewDrainRenderer(ctx.(*engine.GameContext))
	}, render.PriorityDrain)
	registry.RegisterRenderer("quasar", func(ctx any) any {
		return renderer.NewQuasarRenderer(ctx.(*engine.GameContext))
	}, render.PriorityQuasar)
	registry.RegisterRenderer("swarm", func(ctx any) any {
		return renderer.NewSwarmRenderer(ctx.(*engine.GameContext))
	}, render.PrioritySwarm)
	registry.RegisterRenderer("storm", func(ctx any) any {
		return renderer.NewStormRenderer(ctx.(*engine.GameContext))
	}, render.PriorityStorm)
	registry.RegisterRenderer("cleaner", func(ctx any) any {
		return renderer.NewCleanerRenderer(ctx.(*engine.GameContext))
	}, render.PriorityCleaner)
	registry.RegisterRenderer("materialize", func(ctx any) any {
		return renderer.NewMaterializeRenderer(ctx.(*engine.GameContext))
	}, render.PriorityMaterialize)
	registry.RegisterRenderer("teleportline", func(ctx any) any {
		return renderer.NewTeleportLineRenderer(ctx.(*engine.GameContext))
	}, render.PriorityTeleportLine)
	registry.RegisterRenderer("shield", func(ctx any) any {
		return renderer.NewShieldRenderer(ctx.(*engine.GameContext))
	}, render.PriorityShield)
	registry.RegisterRenderer("ember", func(ctx any) any {
		return renderer.NewEmberRenderer(ctx.(*engine.GameContext))
	}, render.PriorityEmber)
	registry.RegisterRenderer("orb", func(ctx any) any {
		return renderer.NewOrbRenderer(ctx.(*engine.GameContext))
	}, render.PriorityOrb)
	registry.RegisterRenderer("lightning", func(ctx any) any {
		return renderer.NewLightningRenderer(ctx.(*engine.GameContext))
	}, render.PriorityLightning)
	registry.RegisterRenderer("missile", func(ctx any) any {
		return renderer.NewMissileRenderer(ctx.(*engine.GameContext))
	}, render.PriorityMissile)
	registry.RegisterRenderer("pulse", func(ctx any) any {
		return renderer.NewPulseRenderer(ctx.(*engine.GameContext))
	}, render.PriorityPulse)
	registry.RegisterRenderer("bullet", func(ctx any) any {
		return renderer.NewBulletRenderer(ctx.(*engine.GameContext))
	}, render.PriorityBullet)
	registry.RegisterRenderer("flash", func(ctx any) any {
		return renderer.NewFlashRenderer(ctx.(*engine.GameContext))
	}, render.PriorityFlash)
	registry.RegisterRenderer("fadeout", func(ctx any) any {
		return renderer.NewFadeoutRenderer(ctx.(*engine.GameContext))
	}, render.PriorityFadeout)
	registry.RegisterRenderer("explosion", func(ctx any) any {
		return renderer.NewExplosionRenderer(ctx.(*engine.GameContext))
	}, render.PriorityExplosion)
	registry.RegisterRenderer("spirit", func(ctx any) any {
		return renderer.NewSpiritRenderer(ctx.(*engine.GameContext))
	}, render.PrioritySpirit)
	registry.RegisterRenderer("splash", func(ctx any) any {
		return renderer.NewSplashRenderer(ctx.(*engine.GameContext))
	}, render.PrioritySplash)
	registry.RegisterRenderer("marker", func(ctx any) any {
		return renderer.NewMarkerRenderer(ctx.(*engine.GameContext))
	}, render.PriorityMarker)
	registry.RegisterRenderer("grayout", func(ctx any) any {
		return renderer.NewGrayoutRenderer(ctx.(*engine.GameContext))
	}, render.PriorityGrayout)
	registry.RegisterRenderer("strobe", func(ctx any) any {
		return renderer.NewStrobeRenderer(ctx.(*engine.GameContext))
	}, render.PriorityStrobe)
	registry.RegisterRenderer("dim", func(ctx any) any {
		return renderer.NewDimRenderer(ctx.(*engine.GameContext))
	}, render.PriorityDim)
	registry.RegisterRenderer("heat", func(ctx any) any {
		return renderer.NewHeatRenderer(ctx.(*engine.GameContext))
	}, render.PriorityHeat)
	registry.RegisterRenderer("indicator", func(ctx any) any {
		return renderer.NewIndicatorRenderer(ctx.(*engine.GameContext))
	}, render.PriorityIndicator)
	registry.RegisterRenderer("statusbar", func(ctx any) any {
		return renderer.NewStatusBarRenderer(ctx.(*engine.GameContext))
	}, render.PriorityStatusBar)
	registry.RegisterRenderer("cursor", func(ctx any) any {
		return renderer.NewCursorRenderer(ctx.(*engine.GameContext))
	}, render.PriorityCursor)
	registry.RegisterRenderer("overlay", func(ctx any) any {
		return renderer.NewOverlayRenderer(ctx.(*engine.GameContext))
	}, render.PriorityOverlay)
	registry.RegisterRenderer("flowfield", func(ctx any) any {
		return renderer.NewFlowFieldDebugRenderer(ctx.(*engine.GameContext))
	}, render.PriorityFlowField)
}

// ActiveSystems returns the ordered list of systems to instantiate
func ActiveSystems() []string {
	return []string{
		"ping",
		"transient",
		"camera",
		"energy",
		"shield",
		"heat",
		"boost",
		"weapon",
		"typing",
		"composite",
		"wall",
		"tower",
		"gateway",
		"loot",
		"glyph",
		"nugget",
		"decay",
		"blossom",
		"gold",
		"materialize",
		"cleaner",
		"fuse",
		"spirit",
		"lightning",
		"missile",
		"navigation",
		"soft_collision",
		"combat",
		"drain",
		"quasar",
		"swarm",
		"storm",
		"pylon",
		"snake",
		"eye",
		"bullet",
		"dust",
		"flash",
		"fadeout",
		"marker",
		"explosion",
		"motion_marker",
		"splash",
		"environment",
		"death",
		"timekeeper",
		"adaptation",
		"genetic",
		"audio",
		"music",
		"diag",
	}
}

// ActiveRenderers returns the ordered list of renderers to instantiate
func ActiveRenderers() []string {
	return []string{
		"ping",
		"chargeline",
		"wall",
		"glyph",
		"sigil",
		"gold",
		"healthbar",
		"pylon",
		"tower",
		"eye",
		"snake",
		"drain",
		"quasar",
		"swarm",
		"storm",
		"cleaner",
		"materialize",
		"teleportline",
		"shield",
		"ember",
		"orb",
		"lightning",
		"missile",
		"pulse",
		"bullet",
		"flash",
		"fadeout",
		"explosion",
		"spirit",
		"splash",
		"marker",
		"grayout",
		"strobe",
		"dim",
		"heat",
		"indicator",
		"statusbar",
		"cursor",
		"overlay",
		"flowfield",
	}
}
