// Code generated by gen-manifest; DO NOT EDIT.

package manifest

import (
	"github.com/lixenwraith/vi-fighter/engine"
	"github.com/lixenwraith/vi-fighter/registry"
	"github.com/lixenwraith/vi-fighter/render"
	"github.com/lixenwraith/vi-fighter/render/renderer"
	"github.com/lixenwraith/vi-fighter/system"
)

// RegisterSystems registers all system factories with the registry
func RegisterSystems() {
	registry.RegisterSystem("ping", func(w any) any {
		return system.NewPingSystem(w.(*engine.World))
	})
	registry.RegisterSystem("energy", func(w any) any {
		return system.NewEnergySystem(w.(*engine.World))
	})
	registry.RegisterSystem("shield", func(w any) any {
		return system.NewShieldSystem(w.(*engine.World))
	})
	registry.RegisterSystem("heat", func(w any) any {
		return system.NewHeatSystem(w.(*engine.World))
	})
	registry.RegisterSystem("boost", func(w any) any {
		return system.NewBoostSystem(w.(*engine.World))
	})
	registry.RegisterSystem("typing", func(w any) any {
		return system.NewTypingSystem(w.(*engine.World))
	})
	registry.RegisterSystem("composite", func(w any) any {
		return system.NewCompositeSystem(w.(*engine.World))
	})
	registry.RegisterSystem("glyph", func(w any) any {
		return system.NewGlyphSystem(w.(*engine.World))
	})
	registry.RegisterSystem("nugget", func(w any) any {
		return system.NewNuggetSystem(w.(*engine.World))
	})
	registry.RegisterSystem("decay", func(w any) any {
		return system.NewDecaySystem(w.(*engine.World))
	})
	registry.RegisterSystem("blossom", func(w any) any {
		return system.NewBlossomSystem(w.(*engine.World))
	})
	registry.RegisterSystem("gold", func(w any) any {
		return system.NewGoldSystem(w.(*engine.World))
	})
	registry.RegisterSystem("materialize", func(w any) any {
		return system.NewMaterializeSystem(w.(*engine.World))
	})
	registry.RegisterSystem("cleaner", func(w any) any {
		return system.NewCleanerSystem(w.(*engine.World))
	})
	registry.RegisterSystem("vampire", func(w any) any {
		return system.NewVampireSystem(w.(*engine.World))
	})
	registry.RegisterSystem("fuse", func(w any) any {
		return system.NewFuseSystem(w.(*engine.World))
	})
	registry.RegisterSystem("spirit", func(w any) any {
		return system.NewSpiritSystem(w.(*engine.World))
	})
	registry.RegisterSystem("lightning", func(w any) any {
		return system.NewLightningSystem(w.(*engine.World))
	})
	registry.RegisterSystem("drain", func(w any) any {
		return system.NewDrainSystem(w.(*engine.World))
	})
	registry.RegisterSystem("quasar", func(w any) any {
		return system.NewQuasarSystem(w.(*engine.World))
	})
	registry.RegisterSystem("swarm", func(w any) any {
		return system.NewSwarmSystem(w.(*engine.World))
	})
	registry.RegisterSystem("dust", func(w any) any {
		return system.NewDustSystem(w.(*engine.World))
	})
	registry.RegisterSystem("flash", func(w any) any {
		return system.NewFlashSystem(w.(*engine.World))
	})
	registry.RegisterSystem("explosion", func(w any) any {
		return system.NewExplosionSystem(w.(*engine.World))
	})
	registry.RegisterSystem("splash", func(w any) any {
		return system.NewSplashSystem(w.(*engine.World))
	})
	registry.RegisterSystem("environment", func(w any) any {
		return system.NewEnvironmentSystem(w.(*engine.World))
	})
	registry.RegisterSystem("death", func(w any) any {
		return system.NewDeathSystem(w.(*engine.World))
	})
	registry.RegisterSystem("timekeeper", func(w any) any {
		return system.NewTimeKeeperSystem(w.(*engine.World))
	})
	registry.RegisterSystem("diagnotics", func(w any) any {
		return system.NewDiagnosticsSystem(w.(*engine.World))
	})
}

// RegisterRenderers registers all renderer factories with priorities
func RegisterRenderers() {
	registry.RegisterRenderer("ping", func(ctx any) any {
		return renderer.NewPingRenderer(ctx.(*engine.GameContext))
	}, render.PriorityGrid)
	registry.RegisterRenderer("splash", func(ctx any) any {
		return renderer.NewSplashRenderer(ctx.(*engine.GameContext))
	}, render.PrioritySplash)
	registry.RegisterRenderer("glyph", func(ctx any) any {
		return renderer.NewGlyphRenderer(ctx.(*engine.GameContext))
	}, render.PriorityEntities)
	registry.RegisterRenderer("sigil", func(ctx any) any {
		return renderer.NewSigilRenderer(ctx.(*engine.GameContext))
	}, render.PriorityEntities)
	registry.RegisterRenderer("gold", func(ctx any) any {
		return renderer.NewGoldRenderer(ctx.(*engine.GameContext))
	}, render.PriorityEntities)
	registry.RegisterRenderer("shield", func(ctx any) any {
		return renderer.NewShieldRenderer(ctx.(*engine.GameContext))
	}, render.PriorityField)
	registry.RegisterRenderer("cleaner", func(ctx any) any {
		return renderer.NewCleanerRenderer(ctx.(*engine.GameContext))
	}, render.PriorityCleaner)
	registry.RegisterRenderer("flash", func(ctx any) any {
		return renderer.NewFlashRenderer(ctx.(*engine.GameContext))
	}, render.PriorityParticle)
	registry.RegisterRenderer("explosion", func(ctx any) any {
		return renderer.NewExplosionRenderer(ctx.(*engine.GameContext))
	}, render.PriorityParticle)
	registry.RegisterRenderer("lightning", func(ctx any) any {
		return renderer.NewLightningRenderer(ctx.(*engine.GameContext))
	}, render.PriorityField)
	registry.RegisterRenderer("spirit", func(ctx any) any {
		return renderer.NewSpiritRenderer(ctx.(*engine.GameContext))
	}, render.PriorityParticle)
	registry.RegisterRenderer("materialize", func(ctx any) any {
		return renderer.NewMaterializeRenderer(ctx.(*engine.GameContext))
	}, render.PriorityMaterialize)
	registry.RegisterRenderer("quasar", func(ctx any) any {
		return renderer.NewQuasarRenderer(ctx.(*engine.GameContext))
	}, render.PriorityMulti)
	registry.RegisterRenderer("swarm", func(ctx any) any {
		return renderer.NewSwarmRenderer(ctx.(*engine.GameContext))
	}, render.PriorityMulti)
	registry.RegisterRenderer("grayout", func(ctx any) any {
		return renderer.NewGrayoutRenderer(ctx.(*engine.GameContext))
	}, render.PriorityPostProcess)
	registry.RegisterRenderer("dim", func(ctx any) any {
		return renderer.NewDimRenderer(ctx.(*engine.GameContext))
	}, render.PriorityPostProcess)
	registry.RegisterRenderer("heatmeter", func(ctx any) any {
		return renderer.NewHeatMeterRenderer(ctx.(*engine.GameContext))
	}, render.PriorityUI)
	registry.RegisterRenderer("rowindicator", func(ctx any) any {
		return renderer.NewRowIndicatorRenderer(ctx.(*engine.GameContext))
	}, render.PriorityUI)
	registry.RegisterRenderer("columnindicator", func(ctx any) any {
		return renderer.NewColumnIndicatorRenderer(ctx.(*engine.GameContext))
	}, render.PriorityUI)
	registry.RegisterRenderer("statusbar", func(ctx any) any {
		return renderer.NewStatusBarRenderer(ctx.(*engine.GameContext))
	}, render.PriorityUI)
	registry.RegisterRenderer("cursor", func(ctx any) any {
		return renderer.NewCursorRenderer(ctx.(*engine.GameContext))
	}, render.PriorityUI)
	registry.RegisterRenderer("overlay", func(ctx any) any {
		return renderer.NewOverlayRenderer(ctx.(*engine.GameContext))
	}, render.PriorityOverlay)
}

// ActiveSystems returns the ordered list of systems to instantiate
func ActiveSystems() []string {
	return []string{
		"ping",
		"energy",
		"shield",
		"heat",
		"boost",
		"typing",
		"composite",
		"glyph",
		"nugget",
		"decay",
		"blossom",
		"gold",
		"materialize",
		"cleaner",
		"vampire",
		"fuse",
		"spirit",
		"lightning",
		"drain",
		"quasar",
		"swarm",
		"dust",
		"flash",
		"explosion",
		"splash",
		"environment",
		"death",
		"timekeeper",
		"diagnotics",
	}
}

// ActiveRenderers returns the ordered list of renderers to instantiate
func ActiveRenderers() []string {
	return []string{
		"ping",
		"splash",
		"glyph",
		"sigil",
		"gold",
		"shield",
		"cleaner",
		"flash",
		"explosion",
		"lightning",
		"spirit",
		"materialize",
		"quasar",
		"swarm",
		"grayout",
		"dim",
		"heatmeter",
		"rowindicator",
		"columnindicator",
		"statusbar",
		"cursor",
		"overlay",
	}
}
