package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

type ComponentDef struct {
	Field string
	Type  string
}

type SystemDef struct {
	Name        string
	Constructor string
}

type RendererDef struct {
	Name        string
	Constructor string
	Priority    string
}

type Definitions struct {
	Components []ComponentDef
	Systems    []SystemDef
	Renderers  []RendererDef
}

// EventDef is one entry in the generated registry
type EventDef struct {
	Name    string // constant identifier, e.g. "EventLevelSetup"
	Payload string // payload struct name; "" = registered as nil
}

// EventDefs is the template input for event/registry_gen.go
type EventDefs struct {
	Events []EventDef
	Count  int // total constants in the block, including EventNone
}

const (
	eventTypeName = "EventType"
	eventNoneName = "EventNone"
	eventPrefix   = "Event"
	payloadSuffix = "Payload"
)

func main() {
	defs := parseDefinitions("definition.go") // cwd is 'manifest/'

	generateFile("../engine/component_store_gen.go", componentStoreTemplate, defs)
	generateFile("build_gen.go", buildTemplate, defs)

	events := parseEvents("../event")
	generateFile("../event/registry_gen.go", eventRegistryTemplate, events)

	fmt.Printf("Generated: %d components, %d systems, %d renderers, %d events\n",
		len(defs.Components), len(defs.Systems), len(defs.Renderers), len(events.Events))
}

func parseDefinitions(path string) Definitions {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		panic(fmt.Sprintf("parse %s: %v", path, err))
	}

	var defs Definitions

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, spec := range genDecl.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Names) == 0 || len(vs.Values) == 0 {
				continue
			}

			name := vs.Names[0].Name
			comp, ok := vs.Values[0].(*ast.CompositeLit)
			if !ok {
				continue
			}

			switch name {
			case "Components":
				defs.Components = parseComponents(comp)
			case "Systems":
				defs.Systems = parseSystems(comp)
			case "Renderers":
				defs.Renderers = parseRenderers(comp)
			}
		}
	}

	return defs
}

func parseComponents(comp *ast.CompositeLit) []ComponentDef {
	var result []ComponentDef
	for _, elt := range comp.Elts {
		lit, ok := elt.(*ast.CompositeLit)
		if !ok || len(lit.Elts) < 2 {
			continue
		}
		result = append(result, ComponentDef{
			Field: extractString(lit.Elts[0]),
			Type:  extractString(lit.Elts[1]),
		})
	}
	return result
}

func parseSystems(comp *ast.CompositeLit) []SystemDef {
	var result []SystemDef
	for _, elt := range comp.Elts {
		lit, ok := elt.(*ast.CompositeLit)
		if !ok || len(lit.Elts) < 2 {
			continue
		}
		result = append(result, SystemDef{
			Name:        extractString(lit.Elts[0]),
			Constructor: extractString(lit.Elts[1]),
		})
	}
	return result
}

func parseRenderers(comp *ast.CompositeLit) []RendererDef {
	var result []RendererDef
	for _, elt := range comp.Elts {
		lit, ok := elt.(*ast.CompositeLit)
		if !ok || len(lit.Elts) < 3 {
			continue
		}
		result = append(result, RendererDef{
			Name:        extractString(lit.Elts[0]),
			Constructor: extractString(lit.Elts[1]),
			Priority:    extractString(lit.Elts[2]),
		})
	}
	return result
}

func extractString(expr ast.Expr) string {
	lit, ok := expr.(*ast.BasicLit)
	if !ok {
		return ""
	}
	return strings.Trim(lit.Value, `"`)
}

func generateFile(path string, tmpl *template.Template, data any) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		panic(fmt.Sprintf("template %s: %v", path, err))
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted for debugging
		os.WriteFile(path+".err", buf.Bytes(), 0644)
		panic(fmt.Sprintf("gofmt %s: %v", path, err))
	}

	if err := os.WriteFile(path, formatted, 0644); err != nil {
		panic(fmt.Sprintf("write %s: %v", path, err))
	}
}

var componentStoreTemplate = template.Must(template.New("store").Parse(`// Code generated by gen-manifest; DO NOT EDIT.

package engine

import (
	"github.com/lixenwraith/vi-fighter/component"
	"github.com/lixenwraith/vi-fighter/core"
)

// Component ID Bitmasks Mapping for Engine-Level Entity Signatures
// Used for O(1) destruction skipping and future fast queries
const (
{{- range $index, $comp := .Components }}
	{{ if eq $index 0 }}{{ $comp.Field }}Bit uint64 = 1 << iota{{ else }}{{ $comp.Field }}Bit{{ end }}
{{- end }}
	PositionBit // Special index designated for spatial grid presence
)

// Component provides typed component store pointers
// Embedded in World, initialized once at world creation
type Component struct {
{{- range .Components }}
	{{ .Field }} *Store[component.{{ .Type }}]
{{- end }}
}

// initComponents creates all component stores
// Called once from NewWorld()
func initComponents(w *World) {
{{- range .Components }}
	w.Components.{{ .Field }} = NewStore[component.{{ .Type }}](w, {{ .Field }}Bit)
{{- end }}
	w.Positions = NewPosition(w, PositionBit)
}

// removeEntity removes entity from every component store
// Caller MUST hold updateMutex
func (w *World) removeEntity(e core.Entity) {

	// Guard against unallocated entity
	mask, ok := w.componentMask[e]
	if !ok {
		return
	}

	// O(1) Fast-Path: If the entity has no components, exit immediately
	if mask == 0 {
		delete(w.componentMask, e)
		return
	}

	// O(1) Skip: Only invoke removal on stores where the bit is strictly present
{{- range .Components }}
	if mask&{{ .Field }}Bit != 0 {
		w.Components.{{ .Field }}.RemoveEntity(e, true)
	}
{{- end }}
	if mask&PositionBit != 0 {
		w.Positions.RemoveEntity(e, true)
	}

	// Remove entity from component mask
	delete(w.componentMask, e)
}

// removeEntitiesBatch removes entities from all stores using batch operations
// Caller MUST hold updateMutex
func (w *World) removeEntitiesBatch(entities []core.Entity) {
	// Union of component signatures: skip every store no entity touches
	var union uint64
	for _, e := range entities {
		union |= w.componentMask[e]
	}
	if union == 0 {
		for _, e := range entities {
			delete(w.componentMask, e)
		}
		return
	}
{{- range .Components }}
	if union&{{ .Field }}Bit != 0 {
		w.Components.{{ .Field }}.RemoveBatch(entities, true)
	}
{{- end }}
	if union&PositionBit != 0 {
		w.Positions.RemoveBatch(entities, true)
	}

	for _, e := range entities {
		delete(w.componentMask, e)
	}
}

// wipeAll clears all component stores
// Caller MUST hold updateMutex
func (w *World) wipeAll() {
{{- range .Components }}
	w.Components.{{ .Field }}.ClearAllComponents()
{{- end }}
	w.Positions.ClearAllComponents()
	
	// Clear component mask
	w.mu.Lock()
	defer w.mu.Unlock()
	clear(w.componentMask)
}
`))

// parseEvents reads the event package and derives the registry from the
// EventType const block. Payload association comes from the doc comment
// annotation: "// EventFoo (FooPayload) description".
//
// An annotation containing '[' or '.' (BatchPayload[T], core.Entity) denotes a
// pooled or scalar payload that is not TOML-decodable; it registers as nil.
func parseEvents(dir string) EventDefs {
	files, names := parsePackage(dir)

	structs := collectStructs(files)

	var (
		block *ast.GenDecl
		src   string
	)
	for i, f := range files {
		for _, d := range f.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST || !isEventTypeBlock(gd) {
				continue
			}
			if block != nil {
				panic(fmt.Sprintf("multiple EventType const blocks (%s, %s); generator expects one", src, names[i]))
			}
			block, src = gd, names[i]
		}
	}
	if block == nil {
		panic(fmt.Sprintf("EventType const block not found in %s", dir))
	}

	return collectEvents(block, structs)
}

// parsePackage parses every non-test, non-generated .go file in dir
func parsePackage(dir string) ([]*ast.File, []string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		panic(fmt.Sprintf("read %s: %v", dir, err))
	}

	names := make([]string, 0, len(entries))
	for _, e := range entries {
		n := e.Name()
		if e.IsDir() || !strings.HasSuffix(n, ".go") ||
			strings.HasSuffix(n, "_test.go") || strings.HasSuffix(n, "_gen.go") {
			continue
		}
		names = append(names, n)
	}
	sort.Strings(names) // deterministic diagnostics

	fset := token.NewFileSet()
	files := make([]*ast.File, 0, len(names))
	for _, n := range names {
		f, err := parser.ParseFile(fset, filepath.Join(dir, n), nil, parser.ParseComments)
		if err != nil {
			panic(fmt.Sprintf("parse %s: %v", n, err))
		}
		files = append(files, f)
	}
	return files, names
}

// collectStructs returns non-generic struct type names declared in the package
func collectStructs(files []*ast.File) map[string]bool {
	structs := make(map[string]bool, 256)
	for _, f := range files {
		for _, d := range f.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, s := range gd.Specs {
				ts, ok := s.(*ast.TypeSpec)
				if !ok || ts.TypeParams != nil {
					continue // skip BatchPayload[T] and friends
				}
				if _, isStruct := ts.Type.(*ast.StructType); isStruct {
					structs[ts.Name.Name] = true
				}
			}
		}
	}
	return structs
}

func isEventTypeBlock(gd *ast.GenDecl) bool {
	for _, s := range gd.Specs {
		vs, ok := s.(*ast.ValueSpec)
		if !ok {
			continue
		}
		if id, ok := vs.Type.(*ast.Ident); ok && id.Name == eventTypeName {
			return true
		}
	}
	return false
}

// collectEvents walks the const block, resolves payloads, and enforces the
// annotation contract. Any violation aborts generation.
func collectEvents(block *ast.GenDecl, structs map[string]bool) EventDefs {
	var (
		defs       []EventDef
		count      int
		errs       []string
		warns      []string
		referenced = make(map[string]bool)
	)

	for _, s := range block.Specs {
		vs, ok := s.(*ast.ValueSpec)
		if !ok {
			continue
		}
		for _, ident := range vs.Names {
			count++
			name := ident.Name

			if name == "_" || name == eventNoneName {
				continue // sentinel and holes are never registered
			}
			if !strings.HasPrefix(name, eventPrefix) {
				errs = append(errs, fmt.Sprintf("%s: EventType constants must be prefixed %q", name, eventPrefix))
				continue
			}

			payload, annotated := docPayload(vs.Doc, name)

			if !annotated {
				// Safety net: catches "added FooPayload, forgot the annotation"
				if c := strings.TrimPrefix(name, eventPrefix) + payloadSuffix; structs[c] {
					errs = append(errs, fmt.Sprintf(
						"%s: struct %s exists but the doc comment carries no payload annotation; write \"// %s (%s) ...\"",
						name, c, name, c))
					continue
				}
				if vs.Doc == nil {
					warns = append(warns, name+": no doc comment")
				}
				defs = append(defs, EventDef{Name: name})
				continue
			}

			switch {
			case payload == "":
				defs = append(defs, EventDef{Name: name})
			case strings.ContainsAny(payload, "[."):
				// Pooled generic or scalar: opaque to TOML, registers as nil
				defs = append(defs, EventDef{Name: name})
			case !structs[payload]:
				errs = append(errs, fmt.Sprintf("%s: annotated payload %s is not a struct in package event", name, payload))
			default:
				referenced[payload] = true
				defs = append(defs, EventDef{Name: name, Payload: payload})
			}
		}
	}

	for s := range structs {
		if strings.HasSuffix(s, payloadSuffix) && !referenced[s] {
			warns = append(warns, s+": declared but referenced by no event")
		}
	}
	sort.Strings(warns)

	for _, w := range warns {
		fmt.Fprintln(os.Stderr, "warning: event:", w)
	}
	if len(errs) > 0 {
		sort.Strings(errs)
		for _, e := range errs {
			fmt.Fprintln(os.Stderr, "error: event:", e)
		}
		panic(fmt.Sprintf("event registry: %d annotation error(s)", len(errs)))
	}

	return EventDefs{Events: defs, Count: count}
}

// docPayload extracts the parenthesized payload type from the doc line that
// opens with the constant name. Returns ("", false) when no annotation exists.
func docPayload(doc *ast.CommentGroup, name string) (string, bool) {
	if doc == nil {
		return "", false
	}
	for _, line := range strings.Split(doc.Text(), "\n") {
		rest, ok := strings.CutPrefix(strings.TrimSpace(line), name)
		if !ok {
			continue
		}
		rest = strings.TrimSpace(rest)
		if !strings.HasPrefix(rest, "(") {
			return "", false // documented, no payload
		}
		end := strings.Index(rest, ")")
		if end < 0 {
			return "", false
		}
		return strings.TrimSpace(rest[1:end]), true
	}
	return "", false
}

var eventRegistryTemplate = template.Must(template.New("events").Parse(`// Code generated by gen-manifest; DO NOT EDIT.

package event

// EventTypeCount is the number of declared EventType constants, including EventNone
// Values are contiguous in [0, EventTypeCount)
const EventTypeCount = {{ .Count }}

// InitRegistry populates the registry from the EventType const block in type.go
// Must be called once at startup
func InitRegistry() {
	if registryInit {
		return
	}
	registryInit = true

{{- range .Events }}
	RegisterType("{{ .Name }}", {{ .Name }}, {{ if .Payload }}&{{ .Payload }}{}{{ else }}nil{{ end }})
{{- end }}

}
`))

var buildTemplate = template.Must(template.New("build").Parse(`// Code generated by gen-manifest; DO NOT EDIT.

package manifest

import (
	"github.com/lixenwraith/vi-fighter/engine"
	"github.com/lixenwraith/vi-fighter/render"
	"github.com/lixenwraith/vi-fighter/render/renderer"
	"github.com/lixenwraith/vi-fighter/system"
)

// BuildSystems constructs every active system in manifest order
// World.AddSystem sorts by Priority(); the sort is stable, so manifest order
// breaks ties between systems sharing a priority constant
func BuildSystems(w *engine.World) []engine.System {
	return []engine.System{
{{- range .Systems }}
		system.{{ .Constructor }}(w),
{{- end }}
	}
}

// BuildRenderers constructs every active renderer paired with its priority
// RenderOrchestrator.Register sorts by priority with a stable index tiebreak,
// so manifest order breaks ties between renderers at the same layer
func BuildRenderers(ctx *engine.GameContext) []render.Registration {
	return []render.Registration{
{{- range .Renderers }}
		{Renderer: renderer.{{ .Constructor }}(ctx), Priority: render.{{ .Priority }}},
{{- end }}
	}
}

// ActiveSystems returns the names of the systems BuildSystems constructs
// Consumed by config validation of region enabled_systems/disabled_systems
func ActiveSystems() []string {
	return []string{
{{- range .Systems }}
		"{{ .Name }}",
{{- end }}
	}
}
`))
